## 1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [29]:
import numpy as np

a = np.arange(12,24)
a


array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

## 2
Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1

In [30]:
a1 = a[np.newaxis, :]
a1


array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [31]:
a2 = a.reshape(12, 1)
a2

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [32]:
a3 = a.reshape(6,2)
a3


array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [33]:
a4 = a.reshape(3, 4)
a4


array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [34]:
a5 = a.reshape(4,3)
a5


array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

## 3
Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [35]:
aa1 = a.reshape(1, -1)
aa1


array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [36]:
aa2 = a.reshape(6, -1)
aa2

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [37]:
aa3 = a.reshape(3, -1)
aa3

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [38]:
aa4 = a.reshape(-1, 4)
aa4

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
aa5 = a.reshape(-1, 6)
aa5

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

## 4
Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

ОТВЕТ: нельзя

In [40]:
aa = a.reshape(12, 1)
aa.ndim == 1


False

## 5
Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [51]:
b = np.random.randn(3, 4)
b


array([[ 1.6071415 , -0.4188217 , -0.95141035, -0.9702617 ],
       [-0.59326046, -1.75254131, -0.04792337,  0.06612755],
       [ 0.49477906, -0.75398089,  1.59154266,  0.45590407]])

In [49]:
bb = b.flatten()
print(bb)


[-0.02284944 -0.11141425  1.31588222 -0.5333285  -0.56244111 -1.87093788
 -0.44838977  0.07231633 -0.07807003  0.50314544  1.37401931 -1.42744513]


## 6
Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [52]:
a = np.arange(20,0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

## 7
Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

ОТвет: Массив a одномерный, массив b двумерный

In [54]:
b = a.reshape(1, 10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

In [55]:
a.ndim == b.ndim


False

## 8
Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [75]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

In [78]:
v = np.vstack([a, b])
v.size

10

## 9
Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [79]:
a = np.arange(0,12)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [80]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [81]:
At = A.T
At


array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [84]:
B = np.dot(A, At)
B


array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

Матрица B имеет размер 4х4
Обратную матрицу найти не возможно так как детерминант равен 0

In [87]:
np.linalg.det(B) == 0


True

## 10
Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [109]:
np.random.seed(42)
a = np.random.random()
a


0.3745401188473625

## 11
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно.

In [110]:
c = np.random.randint(0,16, 16)
c

array([12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3,  7])

## 12
Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [114]:
C = c.reshape(4, 4)
D = C + B * 10
D

array([[  62,  154,  240,  327],
       [ 152,  504,  866, 1229],
       [ 232,  866, 1500, 2130],
       [ 327, 1224, 2123, 3027]])

In [115]:
np.linalg.det(D) # Детерминант

-2813615.999999922

In [117]:
D_inv = np.linalg.inv(D)
D_inv # Обратная Матрица


array([[-0.02586352,  0.0892254 , -0.01380643, -0.02371752],
       [ 0.11828195, -0.15369261, -0.10471649,  0.12330894],
       [-0.08309663,  0.09068402,  0.24850939, -0.20270996],
       [ 0.01324559, -0.0110932 , -0.13045846,  0.09520276]])

In [119]:
np.linalg.matrix_rank(D) # Ранг Матрицы

4

## 13
Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [125]:
razm = D_inv.shape
razm

(4, 4)

In [121]:
D_tmp = D_inv.flatten()
D_second = []
for i in D_tmp:
    if i > 0:
        D_second.append(1)
    else:
        D_second.append(0)
D_second

[0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1]

In [126]:
D_inv = np.array(D_second).reshape(razm)
D_inv

array([[0, 1, 0, 0],
       [1, 0, 0, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 1]])

In [128]:
E = np.where(D_inv == 1, B, C)
E

array([[ 12,  14,  10,   7],
       [ 14,   4,   6, 122],
       [  2,  86, 149,  10],
       [ 32,   4,   3, 302]])